version: '3.8'

services:
  app:
    build: .
    container_name: api_sql_igesta
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/root/.m2
    healthcheck:
      test: ["CMD", "curl", "-f", "https://api-sql-igesta-2ano.onrender.com/igesta/condenas/selecionar"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
