name: API Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  alive_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /alive endpoint
        run: |
          echo "Pingando a API..."
          curl -v --fail https://api-sql-igesta-2ano.onrender.com/igesta/condenas/selecionar
